// audit-logger.js — Audit Trail Logger for CRA Compliance
// Logs all tax calculations, exports, and user actions with timestamps

const AUDIT_LOG_KEY = 'taxsync_audit_log';
const SESSION_KEY = 'taxsync_session_id';
const MAX_LOG_ENTRIES = 1000;
const LOG_RETENTION_YEARS = 6;

/**
 * Audit Logger class for CRA-compliant audit trails
 */
export class AuditLogger {
  /**
   * Generate or retrieve session ID
   * @returns {string} - Session ID
   */
  static getOrCreateSessionId() {
    let sessionId = sessionStorage.getItem(SESSION_KEY);
    if (!sessionId) {
      sessionId = `session-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
      sessionStorage.setItem(SESSION_KEY, sessionId);
    }
    return sessionId;
  }

  /**
   * Generate watermark for exports
   * @returns {object} - Watermark object with metadata
   */
  static generateWatermark() {
    const version = '1.0.0'; // Read from package.json or config
    const timestamp = new Date().toISOString();
    
    return {
      generated_by: 'TaxSyncForDrivers',
      version: version,
      generated_at: timestamp,
      disclaimer: 'This is an estimate. Consult a tax professional for filing.',
      cra_compliant: true,
      audit_trail_id: `audit-${Date.now()}`
    };
  }

  /**
   * Add watermark to export data
   * @param {string} exportData - Export data (CSV or JSON)
   * @param {string} format - Format type ('csv' or 'json')
   * @returns {string|object} - Watermarked export data
   */
  static addWatermarkToExport(exportData, format = 'csv') {
    const watermark = this.generateWatermark();
    
    if (format === 'csv') {
      return `# Generated by ${watermark.generated_by} v${watermark.version}
# Generated at ${watermark.generated_at}
# Audit Trail ID: ${watermark.audit_trail_id}
# ${watermark.disclaimer}

${exportData}`;
    }
    
    // For JSON exports
    return {
      ...watermark,
      data: exportData
    };
  }

  /**
   * Log an action to the audit trail
   * @param {string} action - Action type (calculation, export, receipt_upload, etc.)
   * @param {object} data - Action data
   * @param {object} metadata - Additional metadata
   * @returns {string} - Log entry ID
   */
  static log(action, data, metadata = {}) {
    const logs = this.getAuditLog();
    
    const logEntry = {
      id: `audit-${Date.now()}`,
      timestamp: new Date().toISOString(),
      version: '1.0.0',
      action,
      data,
      metadata: {
        ...metadata,
        sessionId: this.getOrCreateSessionId(),
        userAgent: typeof navigator !== 'undefined' ? navigator.userAgent : 'Node.js'
      }
    };
    
    logs.push(logEntry);
    
    // Keep only last MAX_LOG_ENTRIES to prevent storage bloat
    if (logs.length > MAX_LOG_ENTRIES) {
      logs.shift();
    }
    
    localStorage.setItem(AUDIT_LOG_KEY, JSON.stringify(logs));
    
    return logEntry.id;
  }

  /**
   * Log a calculation
   * @param {object} calculationData - Calculation details
   * @returns {string} - Log entry ID
   */
  static logCalculation(calculationData) {
    return this.log('calculation', calculationData);
  }

  /**
   * Log an export action
   * @param {string} exportType - Type of export (T2125, receipts, etc.)
   * @param {object} data - Export data
   * @returns {string} - Log entry ID
   */
  static logExport(exportType, data) {
    return this.log('export', { exportType, ...data });
  }

  /**
   * Log a receipt upload
   * @param {string} receiptId - Receipt ID
   * @param {object} expense - Expense details
   * @returns {string} - Log entry ID
   */
  static logReceiptUpload(receiptId, expense) {
    return this.log('receipt_upload', { receiptId, expense });
  }

  /**
   * Get all audit logs
   * @returns {Array} - Array of audit log entries
   */
  static getAuditLog() {
    const data = localStorage.getItem(AUDIT_LOG_KEY);
    return data ? JSON.parse(data) : [];
  }

  /**
   * Get logs by action type
   * @param {string} action - Action type to filter by
   * @returns {Array} - Filtered log entries
   */
  static getLogsByAction(action) {
    const logs = this.getAuditLog();
    return logs.filter(log => log.action === action);
  }

  /**
   * Get logs by date range
   * @param {string} startDate - Start date (ISO format)
   * @param {string} endDate - End date (ISO format)
   * @returns {Array} - Filtered log entries
   */
  static getLogsByDateRange(startDate, endDate) {
    const logs = this.getAuditLog();
    const start = new Date(startDate);
    const end = new Date(endDate);
    
    return logs.filter(log => {
      const logDate = new Date(log.timestamp);
      return logDate >= start && logDate <= end;
    });
  }

  /**
   * Get logs by tax year
   * @param {number} year - Tax year
   * @returns {Array} - Filtered log entries
   */
  static getLogsByTaxYear(year) {
    const startDate = `${year}-01-01`;
    const endDate = `${year}-12-31`;
    return this.getLogsByDateRange(startDate, endDate);
  }

  /**
   * Generate audit report for a tax year
   * @param {number} year - Tax year
   * @returns {object} - Audit report summary
   */
  static generateAuditReport(year) {
    const logs = this.getLogsByTaxYear(year);
    
    const actionCounts = {};
    logs.forEach(log => {
      actionCounts[log.action] = (actionCounts[log.action] || 0) + 1;
    });
    
    return {
      year,
      totalEntries: logs.length,
      actionBreakdown: actionCounts,
      firstEntry: logs.length > 0 ? logs[0].timestamp : null,
      lastEntry: logs.length > 0 ? logs[logs.length - 1].timestamp : null,
      logs
    };
  }

  /**
   * Export audit log
   * @param {string} format - Export format ('json' or 'csv')
   * @returns {string} - Formatted audit log
   */
  static exportAuditLog(format = 'json') {
    const logs = this.getAuditLog();
    
    if (format === 'json') {
      return JSON.stringify(logs, null, 2);
    }
    
    // CSV format
    let csv = 'ID,Timestamp,Version,Action,Session ID,User Agent\n';
    
    logs.forEach(log => {
      const userAgent = (log.metadata.userAgent || '').replace(/,/g, ';');
      csv += `${log.id},${log.timestamp},${log.version},${log.action},${log.metadata.sessionId},${userAgent}\n`;
    });
    
    return csv;
  }

  /**
   * Clear old logs (keep only specified years)
   * @param {number} yearsToKeep - Number of years to retain (default 6)
   * @returns {number} - Number of logs deleted
   */
  static clearOldLogs(yearsToKeep = LOG_RETENTION_YEARS) {
    const logs = this.getAuditLog();
    const cutoffDate = new Date();
    cutoffDate.setFullYear(cutoffDate.getFullYear() - yearsToKeep);
    
    const recentLogs = logs.filter(log => {
      const logDate = new Date(log.timestamp);
      return logDate >= cutoffDate;
    });
    
    const deletedCount = logs.length - recentLogs.length;
    
    if (deletedCount > 0) {
      localStorage.setItem(AUDIT_LOG_KEY, JSON.stringify(recentLogs));
    }
    
    return deletedCount;
  }
}
